image: osanamgcj/mobead_image_build
pipelines:
  steps:
  
    - step: &build-app
        name: "Imagem Docker Teste"
        services:
          - docker
        caches:
          - docker
        script:
          - if [ ! -e $BITBUCKET_TAG ]; then TAG=$BITBUCKET_TAG; else TAG=1.0.0-rc; fi;
          - IMAGE=${AWS_ECR_HOST}/api-credito:${TAG}
          - $(aws ecr get-login --no-include-email --region us-east-2)
          - docker build -f Dockerfile . -t ${IMAGE}
          - docker push ${IMAGE}
